travis:
  secure:
    BINSTAR_TOKEN: ZmhR3Yu+Kpio13Tv0nW5/PTmbQB0EzTdV76Xc3azo0vJs98BqCTj70Pd9UjdWTuPgeqjKUFQvXjozU+8xXxkjimk0clLvfbWnkhNjq5G60mVgEkIGjXqam4o6+Q424XDgsBq2pk5+fRHS9oLHo+j68AElH24Ay/1AIYj2NGbKWwcW0WzuDnzCi3CTIumJASDge4MX+tsC3zwZvTtC5gp28Opzny8dnwueGe9D/tO83cEuI99X0YuHMY/gFnnTdqWNI/ru0rFwLBDR3GGF5fQLKrs4sD435tpvsDrJZ987T2hAW4+CzfnUMUxHBn1/VNjL+VhYw90DIPHcETNgtmGDdAtjP5jVMtYKqkpbLwN+MuVv2ThvpAe4g/9Weqm3ULJe4Kav3guahxrtGX7Li0UO/4lgIq05iXojd8heTeH/RD3nymwvt3AxX9TQaPLM2n6KuKeTEGyN6lc5pKGQCwEevMzmBJ6iE0dWyXNEzXn9kMsp1bRSnFCq6ODMAj1q7/rddwQfQXcu1B1L3L9NRUVPtfsaG3DjHDnHX8iCL+5DHt7TUYtGxN9slhC/yDhfK7stkNt2H2IHWHkOsxIp4rO4aO/2P9gfYatdtOhCTe44hq02WnLlLs9hcVpjpDXfqcb5NOygAsLi8BMi1FyCWXmlIrcCK0lJkTGfnxbT+e1jYg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
