travis:
  secure:
    BINSTAR_TOKEN: 6uEhoFxxQKHMsVaf0BWp4w6uZ9VDlUFlBwLFtxGZxEzdPqE5sZBk2XR/oUuhzr4/JORsD4/Mefl3eJuAGTh3ma5px45H9MFtvU0GMpRl+vA7gyNGM6HyNpvyEa/3LMt75AX2qDjFl2bj2morOBh6tFUWYYfTbMngPefLB3/EMQUycy9sykJpYoOOlyFFgkl8YTuwUcGUnhFcWdSvq+ePfSSaX7V3ghc6cKcru/wAe9tJEIokSbMjoJsREbPm+gSyXArSLXNRG9tCrO2njnqgF4SprLumw/QDBETF1v3zHVBZXylkCP+KTc1d28jS7+Ys6DUdcfzuCoHYinB/0ANHbFR2fo6Ng9OPpDhwcZJ2nmQoWa50ozfHiOszo6TlRE/kKXP8s5xmYlaq6BI+iGyn9Q7G/qFV3eret2XJ4N+zqE9Tebu91Khi0KiiHIuCIAP02veihTBX8lG4Q4GtMFw+w9EamkUPYX7Pz5M1Flt+ed3UPRjKe/xDRcJv44S6Vt+Iv6j/iyU59FZWleDLuuZ8QDEa25lX4X1E9uvEs7wPQgSHh4uGlL/ZP+rI28dxAIQO7SwuWqs4k1q/zLwQSBQnrgkQoEdbCXQg2kkU+tuySMqDZMfF/+SWYIr1Qqr9qsgmbyk8AJMqhKHrwNNj7zh9VXbnBYUIq9lqtLauIDyA70U=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
